import type { Metadata } from "next";
import { Inter } from "next/font/google";
import c from "classnames";
import "@/app/globals.css";
import Link from "next/link";

import { MenuItem } from "@/components";
import { menu } from "../../config/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-CN">
      <body className={c(inter.className, "bg-white", "flex")}>
        <div className="container h-screen w-48 bg-slate-950">
          <h1>记账</h1>
          {menu.map((item) => {
            return (
              <MenuItem name={item.name} path={item.path} key={item.path} />
            );
          })}
        </div>
        <div className="content p-6">{children}</div>
      </body>
    </html>
  );
}
